FROM python:3.9-slim

WORKDIR /mlflow

# Install mlflow and sqlalchemy for the database backend
RUN pip install mlflow sqlalchemy boto3

# Expose MLflow port
EXPOSE 5000

# Command to start MLflow server
# It uses the local sqlite db and mlruns folder
CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow.db", \
     "--default-artifact-root", "./mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5000"]